schema = 3

[mod]
  [mod.'github.com/beorn7/perks']
    version = 'v1.0.1'
    hash = 'sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4='

  [mod.'github.com/cespare/xxhash/v2']
    version = 'v2.3.0'
    hash = 'sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.10.1'
    hash = 'sha256-6LBLgsh4nKkMpgRKVsYFEaGDSU1fncBcWVSjKBdfgjU='

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.5.0'
    hash = 'sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/mattn/go-colorable']
    version = 'v0.1.15'
    hash = 'sha256-hH+yMJHjboEDQbv399OEjfc50RgtO/edw0r2sJfxEJg='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.24'
    hash = 'sha256-pmq8KKIb2+qMF3E1cR2B7NAj5joF2tZduyXjIfIlkTk='

  [mod.'github.com/munnerz/goautoneg']
    version = 'v0.0.0-20191010083416-a7dc8b61c822'
    hash = 'sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.4.3'
    hash = 'sha256-CyCjKBN+zUciGhQiaFpq54qv+NDITcuh5U2HmjArow4='

  [mod.'github.com/prometheus/client_golang']
    version = 'v1.24.1'
    hash = 'sha256-HAOFVYyPiU7hVS1XXMMjkbGgTT7/UN0zVHXYOnjr7is='

  [mod.'github.com/prometheus/client_model']
    version = 'v0.6.3'
    hash = 'sha256-uYXpFkXMT4AXWJShrCRnu51vhGQAuAU3LFQhhGVJ+74='

  [mod.'github.com/prometheus/common']
    version = 'v0.71.0'
    hash = 'sha256-94kki7QNQjmL5UFgJfqN5qeLC/dCqMEevxCHHKyMqUk='

  [mod.'github.com/prometheus/procfs']
    version = 'v0.22.0'
    hash = 'sha256-TRwVHKgW4NnPuC6Me38OD57ccM8AfnS7IxtcAx2TAH4='

  [mod.'github.com/rs/zerolog']
    version = 'v1.35.1'
    hash = 'sha256-JMry/37tnOV0ZUCeWRsduxb3WehvbLxUUZfF2l+Cz/s='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.12.0'
    hash = 'sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws='

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

  [mod.'github.com/spf13/cast']
    version = 'v1.10.0'
    hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/spf13/viper']
    version = 'v1.21.0'
    hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.5'
    hash = 'sha256-ygho+GU5kE7vPMx+dZYyNfCaeMjNxj66XmrcVf3afFE='

  [mod.'golang.org/x/sys']
    version = 'v0.48.0'
    hash = 'sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls='

  [mod.'golang.org/x/text']
    version = 'v0.42.0'
    hash = 'sha256-bviKbNmkN4Yf2dpgwmP6yNcZEakCcv1R+YyAxCdJGkY='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.12'
    hash = 'sha256-MKd0AdkWEe2A79mGPzOY5I76nMqTsGJKQNPJOKyOwkQ='

  [mod.'gopkg.in/check.v1']
    version = 'v1.0.0-20190902080502-41f04d3bba15'
    hash = 'sha256-Xl5gjoqU26M+Yxm6Xok5VHVpYT5hItwsN7d2Wj9L020='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
